// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiwN4sTZ_CNnF1uU3AZOoBd1NbILtrAjM',
    appId: '1:638525522858:web:4ae8e31b7b14b0ed3861d3',
    messagingSenderId: '638525522858',
    projectId: 'vr-store-fb0f6',
    authDomain: 'vr-store-fb0f6.firebaseapp.com',
    storageBucket: 'vr-store-fb0f6.appspot.com',
    measurementId: 'G-BZ8WZFVC0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYs8ICVbuEpJRD0KDNFyISOex5wjTW7kk',
    appId: '1:638525522858:android:80fc623c9e25be353861d3',
    messagingSenderId: '638525522858',
    projectId: 'vr-store-fb0f6',
    storageBucket: 'vr-store-fb0f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-_LlNCT6yEUQOLh96eJx2uyE8MoQY7mM',
    appId: '1:638525522858:ios:954f1f51d17163cb3861d3',
    messagingSenderId: '638525522858',
    projectId: 'vr-store-fb0f6',
    storageBucket: 'vr-store-fb0f6.appspot.com',
    iosBundleId: 'com.example.vrstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiwN4sTZ_CNnF1uU3AZOoBd1NbILtrAjM',
    appId: '1:638525522858:web:4a14307b50f3f6933861d3',
    messagingSenderId: '638525522858',
    projectId: 'vr-store-fb0f6',
    authDomain: 'vr-store-fb0f6.firebaseapp.com',
    storageBucket: 'vr-store-fb0f6.appspot.com',
    measurementId: 'G-Y2PZ9M5LQ5',
  );
}
